  export const contactsArray=[  {
      id: 1,
      name: "Kate",
      surname: "Hill",
      fatherName: "Jack",
      gender: "female",
      profession: "Engineer",
      additionalInfo: "Love music",
      getUpdates: true,
    },
    {
      id: 2,
      name: "Helen",
      surname: "Bale",
      fatherName: "Jack",
      gender: "female",
      profession: "Doctor",
      additionalInfo: "Love watching films",
      getUpdates: true,
    },
    {
      id: 3,
      name: "Kate3",
      surname: "Hill3",
      fatherName: "Jack",
      gender: "female",
      profession: "Engineer",
      additionalInfo: "Love nature",
      getUpdates: true,
    },]